// navigator
const HOME_SCREEN = 'HOME_SCREEN';
const SEARCH_SCREEN = 'SEARCH_SCREEN';
const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
const PROFILE_SCREEN = 'PROFILE_SCREEN';

export default {
  HOME_SCREEN,
  SEARCH_SCREEN,
  NOTIFICATION_SCREEN,
  PROFILE_SCREEN,
};
