// navigator
const HOME_SCREEN = 'HOME_SCREEN';
const SEARCH_SCREEN = 'SEARCH_SCREEN';
const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
const PROFILE_SCREEN = 'PROFILE_SCREEN';
const CHAT_SCREEN = 'CHAT_SCREEN';
const HOME_STACK = 'HOME_STACK';
const SEARCH_STACK = 'SEARCH_STACK';
const NOTIFICATION_STACK = 'NOTIFICATION_STACK';
const PROFILE_STACK = 'PROFILE_STACK';

export default {
  HOME_SCREEN,
  SEARCH_SCREEN,
  NOTIFICATION_SCREEN,
  PROFILE_SCREEN,
  CHAT_SCREEN,
  HOME_STACK,
  SEARCH_STACK,
  NOTIFICATION_STACK,
  PROFILE_STACK,
};
